<?php
/**
 * Export Trading Data
 * Supports CSV, Excel (CSV format), and PDF export
 */

require_once 'includes/config.php';
require_once 'includes/functions.php';

if (!isLoggedIn()) {
    redirect('login.php');
}

$format = $_GET['format'] ?? 'csv';
$period = $_GET['period'] ?? 30;

// Get trading data
$db = getDBConnection();
$userId = $_SESSION['user_id'];

// Build date filter
$dateFilter = '';
if ($period !== 'all') {
    $period = (int)$period;
    $dateFilter = "AND created_at >= DATE_SUB(NOW(), INTERVAL $period DAY)";
}

$stmt = $db->prepare("
    SELECT
        DATE_FORMAT(created_at, '%Y-%m-%d %H:%i:%s') as date,
        strategy,
        market,
        direction,
        amount,
        result,
        profit_loss,
        timeframe
    FROM trades
    WHERE user_id = ? $dateFilter
    ORDER BY created_at DESC
");
$stmt->execute([$userId]);
$trades = $stmt->fetchAll(PDO::FETCH_ASSOC);

// Get user info for filename
$user = getUserById($userId);
$filename = 'ZYN_Trade_' . preg_replace('/[^a-zA-Z0-9]/', '', $user['fullname']) . '_' . date('Y-m-d');

switch ($format) {
    case 'csv':
        exportCSV($trades, $filename);
        break;
    case 'excel':
        exportCSV($trades, $filename, true); // Excel-compatible CSV
        break;
    case 'pdf':
        exportPDF($trades, $filename, $user, $period);
        break;
    default:
        exportCSV($trades, $filename);
}

function exportCSV($trades, $filename, $excel = false) {
    $ext = $excel ? '.xls' : '.csv';
    $contentType = $excel ? 'application/vnd.ms-excel' : 'text/csv';

    header('Content-Type: ' . $contentType . '; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $filename . $ext . '"');

    $output = fopen('php://output', 'w');

    // BOM for Excel UTF-8 compatibility
    if ($excel) {
        fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF));
    }

    // Header row
    fputcsv($output, ['Date', 'Strategy', 'Market', 'Direction', 'Amount ($)', 'Result', 'Profit/Loss ($)', 'Timeframe']);

    // Data rows
    $totalPnl = 0;
    $wins = 0;
    $losses = 0;

    foreach ($trades as $trade) {
        fputcsv($output, [
            $trade['date'],
            $trade['strategy'],
            $trade['market'],
            strtoupper($trade['direction']),
            number_format($trade['amount'], 2),
            strtoupper($trade['result']),
            ($trade['profit_loss'] >= 0 ? '+' : '') . number_format($trade['profit_loss'], 2),
            $trade['timeframe']
        ]);

        $totalPnl += $trade['profit_loss'];
        if ($trade['result'] === 'win') $wins++;
        else $losses++;
    }

    // Summary row
    fputcsv($output, []);
    fputcsv($output, ['=== SUMMARY ===']);
    fputcsv($output, ['Total Trades', count($trades)]);
    fputcsv($output, ['Wins', $wins]);
    fputcsv($output, ['Losses', $losses]);
    fputcsv($output, ['Win Rate', count($trades) > 0 ? number_format(($wins / count($trades)) * 100, 1) . '%' : '0%']);
    fputcsv($output, ['Total P&L', ($totalPnl >= 0 ? '+' : '') . '$' . number_format($totalPnl, 2)]);
    fputcsv($output, ['']);
    fputcsv($output, ['Generated by ZYN Trade System', date('Y-m-d H:i:s')]);

    fclose($output);
    exit;
}

function exportPDF($trades, $filename, $user, $period) {
    // Simple HTML-based PDF (for production, use TCPDF or FPDF library)
    header('Content-Type: text/html; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $filename . '.html"');

    $totalPnl = 0;
    $wins = 0;
    $losses = 0;

    foreach ($trades as $trade) {
        $totalPnl += $trade['profit_loss'];
        if ($trade['result'] === 'win') $wins++;
        else $losses++;
    }

    $winRate = count($trades) > 0 ? ($wins / count($trades)) * 100 : 0;

    echo '<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>ZYN Trade Report - ' . htmlspecialchars($user['fullname']) . '</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
        h1 { color: #00d4ff; border-bottom: 2px solid #00d4ff; padding-bottom: 10px; }
        .header { margin-bottom: 30px; }
        .summary { background: #f5f5f5; padding: 20px; border-radius: 10px; margin-bottom: 30px; }
        .summary-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; }
        .summary-item { text-align: center; }
        .summary-value { font-size: 24px; font-weight: bold; }
        .summary-label { color: #666; font-size: 12px; }
        .profit { color: #28a745; }
        .loss { color: #dc3545; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: #00d4ff; color: white; padding: 10px; text-align: left; }
        td { padding: 8px; border-bottom: 1px solid #ddd; }
        tr:nth-child(even) { background: #f9f9f9; }
        .win { color: #28a745; font-weight: bold; }
        .loss { color: #dc3545; font-weight: bold; }
        .footer { margin-top: 30px; font-size: 12px; color: #666; text-align: center; }
        @media print { body { margin: 20px; } }
    </style>
</head>
<body>
    <div class="header">
        <h1>🤖 ZYN Trade System - Trading Report</h1>
        <p><strong>User:</strong> ' . htmlspecialchars($user['fullname']) . '</p>
        <p><strong>Package:</strong> ' . strtoupper($user['package']) . '</p>
        <p><strong>Period:</strong> ' . ($period === 'all' ? 'All Time' : "Last $period Days") . '</p>
        <p><strong>Generated:</strong> ' . date('d M Y H:i') . ' WIB</p>
    </div>

    <div class="summary">
        <h3>📊 Summary</h3>
        <div class="summary-grid">
            <div class="summary-item">
                <div class="summary-value">' . count($trades) . '</div>
                <div class="summary-label">Total Trades</div>
            </div>
            <div class="summary-item">
                <div class="summary-value profit">' . $wins . '</div>
                <div class="summary-label">Wins</div>
            </div>
            <div class="summary-item">
                <div class="summary-value loss">' . $losses . '</div>
                <div class="summary-label">Losses</div>
            </div>
            <div class="summary-item">
                <div class="summary-value">' . number_format($winRate, 1) . '%</div>
                <div class="summary-label">Win Rate</div>
            </div>
        </div>
        <div style="text-align: center; margin-top: 20px;">
            <div class="summary-value ' . ($totalPnl >= 0 ? 'profit' : 'loss') . '">
                ' . ($totalPnl >= 0 ? '+' : '') . '$' . number_format($totalPnl, 2) . '
            </div>
            <div class="summary-label">Total Profit/Loss</div>
        </div>
    </div>

    <h3>📋 Trade History</h3>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Strategy</th>
                <th>Market</th>
                <th>Direction</th>
                <th>Amount</th>
                <th>Result</th>
                <th>P&L</th>
            </tr>
        </thead>
        <tbody>';

    foreach ($trades as $trade) {
        $resultClass = $trade['result'] === 'win' ? 'win' : 'loss';
        echo '<tr>
            <td>' . htmlspecialchars($trade['date']) . '</td>
            <td>' . htmlspecialchars($trade['strategy']) . '</td>
            <td>' . htmlspecialchars($trade['market']) . '</td>
            <td>' . strtoupper($trade['direction']) . '</td>
            <td>$' . number_format($trade['amount'], 2) . '</td>
            <td class="' . $resultClass . '">' . strtoupper($trade['result']) . '</td>
            <td class="' . $resultClass . '">' . ($trade['profit_loss'] >= 0 ? '+' : '') . '$' . number_format($trade['profit_loss'], 2) . '</td>
        </tr>';
    }

    echo '</tbody>
    </table>

    <div class="footer">
        <p>Generated by ZYN Trade System - Zero Emotion, Maximum Profit 🚀</p>
        <p>© ' . date('Y') . ' ZYN Trade. All rights reserved.</p>
    </div>

    <script>window.print();</script>
</body>
</html>';
    exit;
}
